feat: workflow has pub dev publish code.

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -4,9 +4,9 @@ on:
   push:
     branches: [ "main" ]
     tags:
-      - 'v*' # Release tags for the bundle package
-      - 'dio_v*' # Release tags for the dio implementation package
-      - 'core_v*' # Release tags for the core package
+      - 'v[0-9]+.[0-9]+.[0-9]+*' # Release tags for the bundle package
+      - 'dio_v[0-9]+.[0-9]+.[0-9]+*' # Release tags for the dio implementation package
+      - 'core_v[0-9]+.[0-9]+.[0-9]+*' # Release tags for the core package
   pull_request:
     branches: [ "main" ]
 
@@ -118,3 +118,31 @@ jobs:
           asset_path: source_code.zip
           asset_name: flutter_network_layer${{ env.package_name }}.zip
           asset_content_type: application/zip
+
+  publish:
+    needs: release
+    if: startsWith(github.ref, 'refs/tags/')
+    runs-on: ubuntu-latest
+
+    permissions:
+      id-token: write
+
+    steps:
+      - name: determine package name by tag
+        id: package_name
+        run: |
+          if [[ ${{ github.ref }} == refs/tags/dio_v* ]]; then
+            echo "package_name=_dio" >> $GITHUB_ENV
+          elif [[ ${{ github.ref }} == refs/tags/core_v* ]]; then
+            echo "package_name=_core" >> $GITHUB_ENV
+          elif [[ ${{ github.ref }} == refs/tags/v* ]]; then
+            echo "package_name=" >> $GITHUB_ENV
+          else
+            echo "::error::Unknown package name"
+            exit 1
+          fi
+
+      - name: run pub dev publish
+        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
+        with:
+          working-directory: flutter_network_layer${{ steps.package_name.outputs.package_name }}
